### ISSUE TITLE
Version Checker can hang application on load?

### ISSUE THREAD

**Issue by Histidine91** [Lukas22041/LunaLib#9]
Happens when the loading progress bar reaches 100%.

From JVisualVM thread dump:
```

"Thread-3" #20 prio=5 os_prio=0 tid=0x0000017fdd719800 nid=0x5d54 runnable [0x00000079e55fd000]
   java.lang.Thread.State: RUNNABLE
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	- locked <0x000000077f57da10> (a java.net.DualStackPlainSocketImpl)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:613)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:293)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	- locked <0x000000077f57d870> (a sun.net.www.protocol.https.HttpsClient)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1167)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1061)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1577)
	- locked <0x000000077f57cc88> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1505)
	- locked <0x000000077f57cc88> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	- locked <0x000000077f57ca98> (a sun.net.www.protocol.https.HttpsURLConnectionImpl)
	at java.net.URL.openStream(URL.java:1093)
	at lunalib.backend.ui.versionchecker.UpdateInfo$VersionFile.<init>(UpdateInfo.java:193)
	at lunalib.backend.ui.versionchecker.VCModPlugin.onApplicationLoad(VCModPlugin.java:87)
	at lunalib.LunaLibPlugin.onApplicationLoad(LunaLibPlugin.kt:52)
	at com.fs.starfarer.loading.ResourceLoaderState.init(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by Lukas22041** [comment]
Seems to be an issue with my implementation of getting changelogs. 
I likely have to rewrite it to make them loaded earlier in the process so that it doesnt hang on the main thread.

**Comment by Lukas22041** [comment]
Right, gave it a better look, and the actual issue is that the changelog for each mod was loaded twice, once for the local and once for the remote file, and only the remote files are loaded with seperate threads. 

Fixed this behaviour, with which it should only load the changelog once now, and do so without stopping the main thread at all.
